### ISSUE TITLE
Setting up Kanban board for the Ruby Capstone Project - My Catalog

### ISSUE THREAD

**Issue by asharanjith** [asharanjith/My-catalog#21]
[Project link](https://github.com/users/asharanjith/projects/3)

Team Members

Team member #1 [Asha S V](https://github.com/asharanjith)
Team member #2 [Joshua Blue-Jack](https://github.com/Tamunokuro)
Team member #3 [Agasha Bornittah](https://github.com/Bornittah)

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hi Team,  

Your task is complete! 🍾🍾 Congratulations!  🎉💯🌟 

## Highlights 👍
- Board has required number of tasks
- Fair distribution of tasks

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
